### ISSUE TITLE
Error in hc\compiles\zombie_generateHC.sqf, line 75

### ISSUE THREAD

**Issue by DavidFrendin** [DavidFrendin/epoch-hc#10]
rpt

```
"called zombie_generateHC:"
Error in expression <hted;
if(!isNil "_array") then {
_agent addMagazine _loot;
};
};
};
};


hint "e>
  Error position: <addMagazine _loot;
};
};
};
};


hint "e>
  Error addmagazine: Type Nombre, Tableau,Chaîne attendu
File mpmissions\__CUR_MP.sauerland\hc\compiles\zombie_generateHC.sqf, line 75
```

**Comment by TayTayTheKiller** [comment]
I tried fix this for myself by replacing the "//Add some" loot section in wild_spawnZombiesHC.sqf & zombie_generateHC. sqf 

```
    //Add some loot
    _loot = "";
    _array = [];
    _rnd = random 1;
    if (_rnd < 0.2) then {
        _lootType = configFile >> "CfgVehicles" >> _type >> "zombieLoot";
        if (isText _lootType) then {
            _array = [];
            {
                _array set [count _array, _x select 0]
            } count getArray (configFile >> "cfgLoot" >> getText(_lootType));
            if (count _array > 0) then {
                _index = dayz_CLBase find getText(_lootType);
                _weights = dayz_CLChances select _index;
                _loot = _array select (_weights select (floor(random (count _weights))));
                if(!isNil "_array") then {
                    _loot_count =   getNumber(configFile >> "CfgMagazines" >> _loot >> "count");
                    if(_loot_count>1) then {
                        _agent addMagazine [_loot, ceil(random _loot_count)];
                    } else {
                    _agent addMagazine _loot;
                    };
                };
            };
        };
    };
```

No errors after and loot spawns on zombies also I will have a propper sit down to understand how the zombies are working with the HC tomorrow.
 my HC rpt is looking like this right now.

"EHC: Initializing"

/_Removed some junk from rpt here_/

"--HCdospawnRCV:["both",false,false,0.587683,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587683,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587683,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587683,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587683,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587683,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587683,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587683,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587683,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587683,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587685,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587685,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587685,3,-1,200,[1330.55,15072.5,0.00204468]]"
"called wild_spawnZombiesHC:"
"--HCdospawnRCV:["both",false,false,0.587685,3,-1,200,[1330.55,15072.5,0.00204468]]"
"called wild_spawnZombiesHC:"
"--HCdospawnRCV:["both",false,false,0.587685,3,-1,200,[1330.55,15072.5,0.00204468]]"
"called wild_spawnZombiesHC:"
"--HCdospawnRCV:["both",false,false,0.587685,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587685,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587685,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587685,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587685,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587685,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587686,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587686,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587686,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587686,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587686,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587686,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587686,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587686,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587686,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587686,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587686,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587686,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587686,3,-1,200,[1330.55,15072.5,0.00204468]]"
"--HCdospawnRCV:["both",false,false,0.587688,3,-1,200,[1330.55,15072.5,0.00204468]]"

**Comment by DavidFrendin** [comment]
I was trying to solve this by using code from the dayz epoch repo, but this will probably do nicely. Thanks for your help.
