### ISSUE TITLE
File path to zombie_agentHC.fsm wrong in some files

### ISSUE THREAD

**Issue by TayTayTheKiller** [DavidFrendin/epoch-hc#8]
I was getting errors in the HC rpt about not being able to find zombie_agentHC.fsm so went ahead and edited
zombie_agentHC.sqf (line 21)
zombie_generateHC (line 32 & 83)

I replaced 
execFSM "zombie_agentHC.fsm";
with
execFSM "hc\compiles\zombie_agentHC.fsm";

error has gone.

**Comment by DavidFrendin** [comment]
Thanks. commit e34b1e2 should resolve this. Still early in the development ^^

**Comment by TayTayTheKiller** [comment]
No worry's man having fun testing this. there was another error aswell i'll post it in a bit.
Managed to get some npc choppers running off it so far Check the epoch topic if you want to test them :)

**Comment by DavidFrendin** [comment]
Big thanks, I noticed the post - will try it out shortly.
